# SecureVault Production Configuration
# This is a production-ready configuration file with real settings
# All sensitive values should be set via environment variables

server:
  port: 8080
  host: "0.0.0.0"
  mode: "release"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  max_header_bytes: 1048576
  tls_enabled: true
  tls_cert_path: "/etc/securevault/tls/cert.pem"
  tls_key_path: "/etc/securevault/tls/key.pem"
  cors_origins:
    - "https://vault.yourdomain.com"
    - "https://admin.yourdomain.com"
  cors_methods:
    - "GET"
    - "POST" 
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  cors_headers:
    - "Authorization"
    - "Content-Type"
    - "X-Request-ID"
    - "X-CSRF-Token"

database:
  host: "${DB_HOST}"
  port: 5432
  name: "${DB_NAME}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  sslmode: "require"
  timezone: "Asia/Ho_Chi_Minh"
  max_open_conns: 100
  max_idle_conns: 25
  conn_max_lifetime: 3600s
  encryption_key: "${DB_ENCRYPTION_KEY}" # 32-byte key for database encryption
  log_queries: false # Disable in production for performance

redis:
  url: "${REDIS_URL}"
  password: "${REDIS_PASSWORD}"
  db: 0
  tls: true
  pool_size: 50
  min_idle_conns: 10
  dial_timeout: 10s
  read_timeout: 5s
  write_timeout: 5s
  pool_timeout: 10s

security:
  jwt_secret: "${JWT_SECRET}" # 64-byte cryptographically secure secret
  jwt_expiry: 15m
  refresh_token_expiry: 168h # 7 days
  password_min_length: 14
  password_complexity: true
  max_login_attempts: 5
  account_lockout_time: 30m
  session_timeout: 12h
  encryption_algorithm: "AES-256-GCM"
  key_rotation_interval: 24h
  rate_limit_rpm: 100
  hmac_secret: "${HMAC_SECRET}" # 32-byte HMAC signing key
  csrf_secret: "${CSRF_SECRET}" # 32-byte CSRF protection key
  password_history: 24

mfa:
  totp_issuer: "SecureVault"
  totp_key_size: 32
  webauthn_rp_id: "vault.yourdomain.com"
  webauthn_rp_name: "SecureVault"
  webauthn_origin: "https://vault.yourdomain.com"
  
  # Twilio SMS Configuration
  twilio_sid: "${TWILIO_ACCOUNT_SID}"
  twilio_auth_token: "${TWILIO_AUTH_TOKEN}"
  twilio_phone_number: "${TWILIO_PHONE_NUMBER}" # Your Twilio phone number
  
  # Email MFA Configuration
  email_enabled: true
  smtp_host: "${SMTP_HOST}" # e.g., smtp.gmail.com
  smtp_port: 587
  smtp_user: "${SMTP_USER}"
  smtp_password: "${SMTP_PASSWORD}"
  from_email: "noreply@yourdomain.com"
  
  # Pushover Push Notifications
  pushover_enabled: true
  pushover_app_token: "${PUSHOVER_APP_TOKEN}"
  pushover_user_key: "${PUSHOVER_USER_KEY}"
  
  # MFA Policy
  required_methods: 1 # Minimum MFA methods required
  grace_period: 0     # No grace period in production
  max_attempts: 3
  lockout_duration: 15 # 15 minutes

logging:
  level: "info"
  format: "json"
  output: "stdout"
  structured: true
  include_caller: false
  log_requests: true
  log_responses: false

backup:
  enabled: true
  interval: 6h
  retention: 2160h # 90 days
  storage_provider: "s3"
  s3_bucket: "${BACKUP_S3_BUCKET}"
  s3_region: "${AWS_REGION}"
  s3_access_key: "${AWS_ACCESS_KEY_ID}"
  s3_secret_key: "${AWS_SECRET_ACCESS_KEY}"
  encryption_key: "${BACKUP_ENCRYPTION_KEY}" # Separate key for backup encryption
  compress: true
  verify_restore: true

monitoring:
  enabled: true
  metrics_port: 9090
  health_check_port: 8081
  prometheus_enabled: true
  jaeger_enabled: true
  jaeger_endpoint: "${JAEGER_ENDPOINT}"
  log_sampling_rate: 0.1 # Sample 10% of requests

audit:
  enabled: true
  retention_days: 2557 # 7 years for compliance
  blockchain_verification: true
  tamper_detection: true
  real_time_alerts: true
  export_formats:
    - "json"
    - "csv"
    - "parquet"
  storage_provider: "s3"
  archive_after_days: 365

compliance:
  gdpr_enabled: true
  data_retention_days: 2557 # 7 years
  right_to_be_forgotten: true
  data_portability: true
  consent_management: true
  privacy_by_design: true
  data_classification: true

performance:
  cache_ttl: 300s # 5 minutes
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_size: 20
    cleanup_interval: 60s
  connection_pooling:
    max_open: 100
    max_idle: 25
    max_lifetime: 3600s
  query_optimization:
    prepared_statements: true
    connection_reuse: true
    batch_size: 100

encryption:
  master_key_rotation: 90 # days
  item_key_rotation: 30   # days
  quantum_resistant: true
  key_derivation: "scrypt"
  kdf_iterations: 32768
  memory_factor: 8
  parallelization: 1
  key_size: 32

security_policies:
  password_policy:
    min_length: 14
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_symbols: true
    max_age_days: 90
    history_count: 24
    lockout_attempts: 5
    lockout_duration: 30 # minutes
  
  session_policy:
    max_concurrent: 3
    idle_timeout: 12h # 12 hours
    absolute_timeout: 24h # 24 hours
    ip_binding: true
    device_tracking: true
  
  access_policy:
    ip_whitelist_enabled: false
    ip_blacklist_enabled: true
    geo_blocking_enabled: false
    device_trust_required: false
    risk_based_auth: true

integrations:
  ldap:
    enabled: false
    server: "${LDAP_SERVER}"
    port: 389
    bind_dn: "${LDAP_BIND_DN}"
    bind_password: "${LDAP_BIND_PASSWORD}"
    user_search_base: "${LDAP_USER_BASE}"
    group_search_base: "${LDAP_GROUP_BASE}"
  
  saml:
    enabled: false
    idp_url: "${SAML_IDP_URL}"
    idp_cert: "${SAML_IDP_CERT}"
    sp_cert: "${SAML_SP_CERT}"
    sp_key: "${SAML_SP_KEY}"
  
  breach_detection:
    enabled: true
    api_endpoint: "https://api.pwnedpasswords.com/range/"
    timeout: 10s
    rate_limit: 10 # requests per minute
    cache_duration: 24h

# Environment-specific overrides
environment: "production"
debug: false
profiling: false
development_mode: false

# Version and build information
version: "1.0.0"
build_date: "2024-01-15T00:00:00Z"
git_commit: "production-build"